name: Bug
description: Something is broken or incorrect
title: "bug: "
labels: ["type:bug"]
body:
  - type: input
    id: feature_slug
    attributes:
      label: Feature Slug (optional)
      description: If the bug belongs to a specific feature or initiative, provide the slug.
      placeholder: "oauth-token-refresh"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong?
      placeholder: "X fails when Y happens."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Logs, screenshots, stack traces, links. Redact secrets.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        OS:
        Runtime/Version:
        Browser (if relevant):
        Commit/Branch:
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - S0 (blocks work)
        - S1 (major)
        - S2 (minor)
        - S3 (cosmetic)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Verifiable checklist items.
      placeholder: |
        - [ ] Repro fixed
        - [ ] Regression test added (if appropriate)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (urgent)
        - P1 (high)
        - P2 (medium)
        - P3 (low)
    validations:
      required: false

  - type: input
    id: owner
    attributes:
      label: Owner
      description: GitHub username (optional).
      placeholder: "@your-handle"
    validations:
      required: false
