name: Bug
description: Something is broken or incorrect
title: "bug: "
labels: ["type:bug"]
body:
  - type: input
    id: feature_slug
    attributes:
      label: Feature Slug (optional)
      description: If this bug belongs to a specific feature.
      placeholder: "oauth-token-refresh"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Logs, screenshots, stack traces, links.
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - S0 (blocks work)
        - S1 (major)
        - S2 (minor)
        - S3 (cosmetic)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Repro fixed
        - [ ] Regression test added (if appropriate)
    validations:
      required: true
