name: Feature (Form)
description: A user-visible feature tracked by a plan in plans/*.md
title: "feature: "
labels: ["type:feature"]
body:
  - type: input
    id: feature_slug
    attributes:
      label: Feature Slug
      description: Kebab-case slug. Should match the plan filename in plans/.
      placeholder: "league-ingestion"
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: One paragraph describing the outcome.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / Background
      description: Links and background needed to understand why.
      placeholder: |
        - Plan: plans/<feature_slug>.md
        - Links: ...
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: In scope and out of scope.
      placeholder: |
        In scope:
        - ...
        Out of scope:
        - ...
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / Ordering Notes
      description: Sequencing considerations or related work.
    validations:
      required: false

  - type: textarea
    id: assumptions
    attributes:
      label: Assumptions / Unknowns
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Risks
    validations:
      required: false

  - type: textarea
    id: success
    attributes:
      label: Success Criteria
      description: Verifiable checklist items.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing / Verification
      description: How you will verify feature success.
      placeholder: |
        - [ ] Integration/E2E: ...
        - [ ] Manual smoke test: ...
    validations:
      required: true

  - type: textarea
    id: plan_metadata
    attributes:
      label: Plan Metadata
      placeholder: |
        - Path: plans/<feature_slug>.md
        - Task count: ...
        - Research tasks: ...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: false

  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - S
        - M
        - L
        - XL
    validations:
      required: false
