name: Research
description: Investigate unknowns before implementation
title: "research: "
labels: ["type:research"]
body:
  - type: textarea
    id: question
    attributes:
      label: Research Question
      description: What do we need to learn/decide?
    validations:
      required: true

  - type: textarea
    id: success
    attributes:
      label: Done Means
      description: What artifact will this produce?
      placeholder: |
        - docs/research/<topic>.md with:
          - verified facts + sources
          - unknowns explicitly labeled
          - recommended approach
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope / Constraints
      placeholder: |
        In scope:
        - ...
        Out of scope:
        - ...
    validations:
      required: false

  - type: dropdown
    id: timebox
    attributes:
      label: Timebox
      options:
        - 30 minutes
        - 1 hour
        - 2 hours
        - 4 hours
    validations:
      required: true
