name: Research (Form)
description: Investigate unknowns before implementation
title: "research: "
labels: ["type:research"]
body:
  - type: input
    id: feature_slug
    attributes:
      label: Feature Slug
      description: Slug of the parent feature.
      placeholder: "oauth-token-refresh"
    validations:
      required: true

  - type: input
    id: parent
    attributes:
      label: Parent Feature Issue
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: One-sentence outcome.
    validations:
      required: false

  - type: textarea
    id: question
    attributes:
      label: Questions / Unknowns
      description: What do we need to learn or decide?
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: Done Means
      description: What artifact will this produce?
      placeholder: |
        - docs/research/<topic>.md with:
          - verified facts + sources
          - unknowns explicitly labeled
          - recommendation
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / Background
      placeholder: |
        - Plan: plans/<feature-slug>.md — R1
    validations:
      required: false

  - type: textarea
    id: links
    attributes:
      label: Relevant Links
    validations:
      required: false

  - type: textarea
    id: depends_on
    attributes:
      label: Depends on
      placeholder: |
        - None
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope / Constraints
      placeholder: |
        In scope:
        - ...
        Out of scope:
        - ...
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false

  - type: textarea
    id: testing
    attributes:
      label: Testing / Verification
      placeholder: |
        - [ ] ...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: false

  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - S
        - M
        - L
        - XL
    validations:
      required: false

  - type: dropdown
    id: timebox
    attributes:
      label: Timebox
      options:
        - 30 minutes
        - 1 hour
        - 2 hours
        - 4 hours
    validations:
      required: true
