name: Task (Form)
description: An implementation task under a feature plan
title: "task: "
labels: ["type:task"]
body:
  - type: input
    id: feature_slug
    attributes:
      label: Feature Slug
      description: Kebab-case slug of the parent feature.
      placeholder: "league-ingestion"
    validations:
      required: true

  - type: input
    id: parent
    attributes:
      label: Parent Feature Issue
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: One-sentence outcome.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / Background
      placeholder: |
        - Plan: plans/<feature_slug>.md — T1
        - Notes: ...
    validations:
      required: false

  - type: textarea
    id: depends_on
    attributes:
      label: Depends on
      placeholder: |
        - None
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope
      placeholder: |
        In scope:
        - ...
        Out of scope:
        - ...
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Proposed Approach
      description: High-level steps only.
      placeholder: |
        - ...
        - ...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing / Verification
      placeholder: |
        - [ ] Unit tests: ...
        - [ ] Manual checks: ...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (urgent)
        - P1 (high)
        - P2 (medium)
        - P3 (low)
    validations:
      required: false

  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - S (≤ 1h)
        - M (1–3h)
        - L (3–6h)
        - XL (> 6h)
    validations:
      required: true
