name: Task (Form)
description: A single, implementation-sized unit of work
title: "task: "
labels: ["type:task"]
body:
  - type: input
    id: feature_slug
    attributes:
      label: Feature Slug
      description: Slug of the parent feature.
      placeholder: "oauth-token-refresh"
    validations:
      required: true

  - type: input
    id: parent
    attributes:
      label: Parent Feature Issue
      description: Link the parent feature issue (recommended).
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What outcome should exist when this is done?
      placeholder: "Add X so users can Y."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / Background
      description: Only what is necessary.
      placeholder: |
        - Plan: plans/<feature-slug>.md — T3
        - Notes: ...
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is in scope (and explicitly out of scope).
      placeholder: |
        In scope:
        - ...
        Out of scope:
        - ...
    validations:
      required: false

  - type: textarea
    id: approach
    attributes:
      label: Proposed Approach
      description: High-level steps only.
      placeholder: |
        - ...
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Verifiable checklist items.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing / Verification
      placeholder: |
        - [ ] Unit tests: ...
        - [ ] Manual checks: ...
    validations:
      required: false

  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - S (≤ 1h)
        - M (1–3h)
        - L (3–6h)
        - XL (> 6h; consider splitting)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (urgent)
        - P1 (high)
        - P2 (medium)
        - P3 (low)
    validations:
      required: false
